### ISSUE TITLE
CREATE NEW TRADE SET WITH RAW TEXT

### ISSUE THREAD

**Issue by Nassiotrader** [MarcelBeining/EazeBot#31] opened 2021-02-21 21:30 UTC
Dear Marcel
Again I have to say thank you for sharing this amazing code with us because it is very useful and easy to use , I am student of master of communication and I am trading in my free time. Before I ran this bot I had to check the binance every hour to check my positions are reached or not or even how much I earned or lost ! but now with this amazing bot I can check everything very easy.
I tried to change your code just to add one more feature but unfortunately I couldn't do that ( I am not a programmer and tried to do that by searching in google :D ) so I decided to ask you one more time and even I am ready to pay for that if you have free time please add this feature and share the code with us .
the feature is CREATE NEW TRADE SET WITH RAW TEXT for example just by sending this message to the bot it sets everything :

BNB/USDT
QUANTITY 100
ENTRY 3.060 - 3.090
TARGETS 3.400 - 3.650 - 4.000 - 4.350 - 4.666 - 5.000 
STOP LOSS DAILY BELOW 2.818

Because to create a new trade set and going through the steps taking time and even with this feature we can share a signal with friends and use it,  Please Please Please try to add this because so far few of my friends start using it and for sure by earning some money they also will donate to your address.

thank you 
Nassio

**Comment by MarcelBeining** [comment] 2021-02-21 23:32
Dear Nassio.
That's an interesting feature, and of course I am open to donations as incentives for this :-)
Of.course such a feature comes with the risk that a typo in the text leads to a wrong trading set and the raw text should always be in the same format to to work.
One thing that is not clear to me is the multiple numbers. Should it be in the way that at each given price a part of the buy should be executed? I.e. in your example bnb for 50 usd should be bought at 3.060 and bnb for 50 usd at 3.090 and the bought bnbs will be sold a sixth at each given price?

**Comment by Nassiotrader** [comment] 2021-02-22 00:21
Dear Marcel
every time I wrote an issue or something here you shocked me by fast replying  , thanks for reply, 
1. regarding the risk I have to say yes it has to flow a pattern and always should be in the same format( as other paid bots work ) , if everyone who is using this bot flow the pattern so there is no risk at all, even bot can recognise that if all the parameters are specified correctly then it opens the trade. 
2. regarding the numbers exactly as you said there is two entry points(bot divides the quantity in two parts), it is the best way to open a trade with low risk in such a way that there is two entry points so if price comes lower than your first entry and second entry reached then your average would be better than the first entry but if price grows up and hit the sell target bot can cancel the second entry ( I dont want to make it complicated but there is lots of feature can be added in future).and total coins that have bought will sell in 6 targets.
I hope that I could explain clearly but anyway if you need I can explain more .

**Comment by MarcelBeining** [comment] 2021-02-23 00:07
Hi @Nassiotrader ,
I have implemented your wish with [version 2.11.1](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.11.1).
After clicking "New Trade Set" and choosing an exchange, you are prompted to either name the trading pair (behavior as before) or paste in a signal text in the format you gave to me. It supports normal stop loss (STOP LOSS BELOW x), daily-close stop loss (STOP LOSS DAILY BELOW x) and weekly-close stop loss (STOP LOSS WEEKL BELOW x).
If you are satisfied, leave a kind donation via GitHub Sponsors (see button in the upper right) or one of the addresses you find in the bot when clicking "Bot Info" and then "Donate". Enjoy :-)

**Comment by MarcelBeining** [comment] 2021-02-23 00:09
PS: Please be aware, that problems arise if your quantity and levels lead to too low amounts to buy/sell. In that case the bot will notify you that the exchange does not allow such low amounts/ prices / etc. for the trading pair

**Comment by Nassiotrader** [comment] 2021-02-23 09:42
Hi @MarcelBeining 
Thank you so much , I'm so happy now and I'm going to use it right now I will write my feedback and I'll donate for sure 🙏🏻🙏🏻🙏🏻👍🏻👍🏻👍🏻

**Comment by Nassiotrader** [comment] 2021-03-12 09:50
Dear @MarcelBeining there is always an error like this every time I'm sending auto trade signal to the bot : 

ERROR:  Cannot activate trade set because the total amount you (still) want to sell (91.31 ALGO) exceeds the total amount you want to buy (91.22 ALGO after fee subtraction) and the amount you already have in this trade set (0 ALGO). Please adjust the trade set!

I was trying to find the formula that you wrote just to change it if it's possible sell the amount it bought minus 1% of it bought :

Amount_to_sell = Amount_bought - ( amount_bought * 1/100 )

**Comment by MarcelBeining** [comment] 2021-03-14 13:55
Hi @Nassiotrader ,
yeah, finding the maximal possible value is very difficult, as different exchanges are rounding numbers differently and fees are sometimes subtracted from the base currency, sometimes from the coin currency, and sometimes you pay them with an exchange token such as BNB.. I will try to fix it within the next days.

**Comment by MarcelBeining** [comment] 2021-03-14 14:25
@Nassiotrader 
Would you mind sending me an example trade text that leads to the error? Cannot reproduce it with my test text.

**Comment by Nassiotrader** [comment] 2021-03-15 11:41
Dear @MarcelBeining 
Thank you so much for consideration , actually I changed the code and its working now ( I now its not a proper way but solve the problem ) and here what I changed if you compare with original : 

amount_per_buy = [float(ct.exchange.amountToPrecision(
                                                symbol, quantity / (len(entries) * price))) for price in entries]
                                            Amount = sum(amount_per_buy)
                                            Amount = (Amount - ((2/100)*Amount))
                                            amount_per_sell = [float(
                                                ct.exchange.amountToPrecision(symbol,
                                                                              Amount / len(targets)))
                                                              ] * len(targets)
                                            
                                            # fixing the precision rounding difference
                                            amount_per_sell[-1] = float(ct.exchange.amountToPrecision(
                                                symbol, amount_per_sell[-1] -
                                                (sum(amount_per_sell) - Amount)))
                                            assert sum(amount_per_sell) <= sum(amount_per_buy)

**Comment by Nassiotrader** [comment] 2021-03-15 11:44
@MarcelBeining 
Here is two example of raw text that bot could not manage it ( maybe price is changed now ) 
example 1 : 
BZRX/USDT
QUANTITY 100
ENTRY 0.5025 - 0.4625
TARGETS 0.5800 - 0.6320 - 0.6760 - 0.6760 - 0.7220 - 0.7800 - 0.9100  
STOP LOSS DAILY BELOW 0.4220

example 2 : 
ALGO/USDT
QUANTITY 100
ENTRY 1.0900 - 1.1000
TARGETS 1.2300 - 1.3700 - 1.5000 - 1.6500 - 1.8000 - 2.0000 - 2.2000   
STOP LOSS DAILY BELOW 0.9700

**Comment by Nassiotrader** [comment] 2021-03-15 11:55
@MarcelBeining 
Dear Marcel please add a USDT address to your donation list because transfer cost of eth and btc is high now so it would be easer for friends to send you USDT ( ERC20 network is cheap ) 
here is some more features that would perfect if you can add in future : 
1. Stop loss 4h candle 
2. cancel buy order if sell order is reached 
3. showing the status of trade set just the open trades pairs ( as a inline button ) and by touch the pair shows the information

thank you so much

**Comment by MarcelBeining** [comment] 2021-03-21 10:30
@Nassiotrader 
The problem is fixed in [v2.12.0](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.12.0).
In older version there was an assumption that if there is more than 0.5 BNB in your account, you probably pay fees with BNB. As the binance API now allows to check if you are paying with BNB or not and there are APIs available to convert the fee cost into the corresponding BNB values, I was able to implement the fee calculation in a more convenient way :-)

PS: USDT address has been added to the donation lists ;-)

**Closed by MarcelBeining** 2021-03-21 10:30 UTC
Labels: enhancement

**Comment by MarcelBeining** [comment] 2021-03-21 10:31
For more wishes, please open a new issue (per wish). This makes it easier for me, thanks.
